### ISSUE TITLE
Add more of the calculation

### ISSUE THREAD

**Issue by elashoffb** [AntoineSoetewey/statistics-101#4]
In the 201 app, all the calculations are worked through in detail.  In the 101 app though, just the final answer is given.  I think you may have meant to add more, because in the instructions for using the app, you mention the entire answer.  Here is a screenshot of the instructions, and of what I see in the app.
![app101](https://user-images.githubusercontent.com/5251368/118563176-f14c1b80-b722-11eb-827e-dd1818b4c4f3.png)

![app101 instructions](https://user-images.githubusercontent.com/5251368/118563187-f610cf80-b722-11eb-90f0-8e360a62bd12.png)

My students love your apps!
Thanks,

Barbara Elashoff
Instructor at UC Berkeley extension

**Comment by AntoineSoetewey** [comment]
Dear Barbara,

Thanks for your feedback.

If I understand correctly, you'd like to see the step (439-402)/22?

I'll add it as soon as I find some time (probably by the end of next week).

Regards,
Antoine

**Comment by AntoineSoetewey** [comment]
Dear Barbara,

Changes have been implemented in https://github.com/AntoineSoetewey/statistics-101/commit/df29a07cfca3b0d88b2a8071ce7a72ef8e85d399.

See the final result : https://antoinesoetewey.shinyapps.io/statistics-101/

Let me know if you have any other remarks.

Regards,
Antoine
